import React from "react"
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { AosInit } from "./_components/Aos-init";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Adicione os pesos desejados
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.variable} antialiased`}>
//         {children}
//         <AosInit/>
//       </body>
//     </html>
//   );
// }
